### ISSUE TITLE
support loading 16 bit images

### ISSUE THREAD

**Issue by targos** [image-js/core#4]
see https://github.com/arian/pngjs
it may be necessary to fork the library or to find another one that suits our needs

**Comment by targos** [comment]
https://www.npmjs.com/search?q=png

**Comment by lpatiny** [comment]
https://en.wikipedia.org/wiki/Portable_Network_Graphics

The problem is that in a Canvas all the images are RGBA with 8 bits per channel.
However for some microscopy images the number of bits may be higher. It may be 16 bits grayscale or 48 bits RGB images. We should not loose this high resolution while making the processing of those images. 
It is therefore required to find another way to load the data that will directly create the correct corresponding Image Type.

**Comment by lpatiny** [comment]
The type is supported and should be checked by all the methods using the bitDepth attribute

**Comment by targos** [comment]
I reopen the issue because we still have no way to load 16 bit images

**Comment by targos** [comment]
Supported for PNG (https://github.com/image-js/png-js) and greyscale TIFF (https://github.com/image-js/tiff-js)
